# Generated by Django 5.1.3 on 2024-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('citizenship', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
    ]
