# Generated by Django 5.1.3 on 2024-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('citizenship', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('country_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'personal_information',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
